---
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11@sha256:1c457b3b83ab12cd9d8dbf75e1389fd163f2b77ac561d758c6d3896919686b2c

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  build:
    docker:
      - image: circleci/node:9.11@sha256:1c457b3b83ab12cd9d8dbf75e1389fd163f2b77ac561d758c6d3896919686b2c
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  # lint:
  #   docker:
  #     - image: circleci/ruby:2.4.1
  #   steps:
  #     - checkout
  #     - run: gem install --update overcommit
  #     - run: pip install yamllint --user
  #     - run: overcommit --install
  #     - run: overcommit --sign
  #     - run: overcommit --sign pre-commit
  #     - run: overcommit --run

  deploy:
    docker:
      - image: circleci/node:9.11@sha256:1c457b3b83ab12cd9d8dbf75e1389fd163f2b77ac561d758c6d3896919686b2c
    steps:
      - checkout
      - run: npm install
      - run: ./.circleci/deploy-ghpages.sh
      # - run: ./.circleci/notify-github.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build
      # - lint
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - feature/circle-ci
                - master
